### ISSUE TITLE
Error: Failed to parse gitignore

### ISSUE THREAD

**Issue by dten** [vmchale/tin-summer#3]
No idea where the bad file is but sn died :(

```
PS C:\Users\David> sn ar
Error: Failed to parse gitignore
```

**Comment by vmchale** [comment]
Hmm okay. I released a patch which make the failure a bit more graceful. I'm going to keep this open for the time being; if you see which file produced the error do tell me!

Thanks for the bug report by the way.

**Comment by dten** [comment]
```
PS C:\Users\David> sn ar
Error: Failed to parse gitignore at: .\.cargo\registry\src\github.com-1ecc6299db9ec823\racer-2.0.9\.gitignore
Error: path '.\AppData\Local\ElevatedDiagnostics' does not exist.
```

Here's as far as I got now :)

the gitignore it doesn't like looks like this 
```
\#*
src/scopes
!.travis.yml
*tmpfile*
*.racertmp
target/
*.py[cod]
.vscode/**
```

**Comment by vmchale** [comment]
Okay, I've made it less zealous about what it considers a failure necessitating that we abort the command. This *should* fix things, so let me know if it doesn't.

Thanks again for your patience.
