### ISSUE TITLE
Remove `update` command

### ISSUE THREAD

**Issue by nivkner** [vmchale/tin-summer#7]
I don't think a small command line utility should have a built in update command. That task is best left for an out of band mechanism such as `cargo install` or a package manager.

It is fine to have precompiled binaries ready for download but please reconsider making an install script a primary way of installing and updating this tool.

**Comment by vmchale** [comment]
The update subcommand just calls a `bash` script. It doesn't make anything more "heavyweight" in terms of dependencies or binary size.
